on:
  workflow_dispatch: # manually trigger CI
  push:
    branches: [ master ]

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout resume
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          repository: Devin-Yeung/resume
          path: resume
          submodules: true

      - name: Compile resume
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: resume
          root_file: |
            resume-en.tex
            resume-cn.tex
          extra_fonts: fonts/*
          latexmk_use_xelatex: true
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f

      - name: Install pdf2htmlEX
        run: |
          wget "https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/v0.18.8.rc1/pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-focal-x86_64.deb" -O pdf2htmlEX.deb
          sudo apt install ./pdf2htmlEX.deb
          sudo apt install -y ttfautohint

      - name: Convert resume to html
        run: |
          pdf2htmlEX  --external-hint-tool=ttfautohint \
                      --font-size-multiplier 1 \
                      --fit-width 1024 \
                      resume/resume-en.pdf static/assets/resume/resume-en.html

      - name: Use resume as assets
        run: mv resume/resume-en.pdf static/assets/resume

      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          # TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
